# Generated by Django 4.1.5 on 2023-01-20 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='appUser',
            new_name='User',
        ),
    ]
